### ISSUE TITLE
Where the OData validation tool need to be put on OData.org site?

### ISSUE THREAD

**Issue by RongfangWang** [ODataOrg/odataorg.github.io#20]
Odata validation tool is a tool for validating OData rules. On old site, the tool link was located first menu tag, but now the first menu are changed. Please tell us where we can put this link on current site?

**Comment by dingeins** [comment]
Hi @RongfangWang , Liang raised this to us, too. 

We're now working on the refactor of the site. The site will go through another update next month and the entry for your tool was planned for that update so it doesn't appear now.

But since you've raised the problem, we'll have a look at the site and add it back to an appropriate place for you now.

**Comment by RongfangWang** [comment]
Hi @dingeins , thanks for your quick response. Great, wait for your good news.

**Comment by dingeins** [comment]
Hi @RongfangWang , the Validator is added back to a newly created top-level nav item "Tools".

Closing the issue.
