### ISSUE TITLE
Can we develop odata service with Dapper instead of using Entity Framework?

### ISSUE THREAD

**Issue by maheshreeram** [ODataOrg/odataorg.github.io#62]
Hi, I have started reading OData today. Could you please help me in clarifying my doubt if we can use Dapper to develop OData service.

**Comment by dingeins** [comment]
Yes, you may use Entity Framework to develop OData services if you are on .NET. Here are some examples: 

- http://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/create-an-odata-v4-endpoint
- http://odata.github.io/RESTier/#01-02-Bootstrap

**Comment by maheshreeram** [comment]
Hi Dingeins,

Thanks for the swift response. Could you please provide me some examples to develop OData Services with Dapper

**Comment by dingeins** [comment]
I'm afraid I'm not familiar with Dapper. But generally speaking, the OData service stacks (e.g. the Web API for OData) doesn't assume any storage or ORM. It'd surprise me if you can't use Dapper with them.

**Comment by maheshreeram** [comment]
Thanks Dingeins. I have created a sample OData service using Dapper.Thanks for your valuable inputs once again.

**Comment by shahriarhossain** [comment]
@maheshreeram : do you have any public repository from where I can see how you have integrated dapper and OData?

**Comment by darthdaniel85** [comment]
I don't think you guys are getting @maheshreeram question. EF offers out of the box a nice integration with OData by which every url-query gets translated to linq and so EF can perform efficient queries to the DB. If you don't use EF you can still use OData totally independent of any ORM... but you will end up bringing a whole table to memory just to select 1 field. 

I think what @maheshreeram is asking is if Dapper has the same integration with OData as Entity Framework.

**Comment by TehWardy** [comment]
Yeh I was just thinking that ...
This question feels far from answered IMO, it's routed around the complexity of queries that can be generated from OData query strings.
the net result is that dapper needs decent LINQ to DB integration to work in the same way.

It's non trivial IMO and Dapper whilst offering some decent tooling for "single set based questions with mapping" it gets interesting when you start using complex functions like includes or grouping  ... or when you want to take advantage of cross set referencing between your OData model sets.

This blog post i just dug up talks about the approach in some detail ...

https://jtabuloc.wordpress.com/2018/06/12/migration-from-entity-framework-to-dapper/

... it would be really cool if OData could be put in to "flat set mode" or something to allow the joining of includes / sub queries in the API layer instead of the DB model that way the OData framework could be doing simpler "SELECT * FROM TableX" queries with Dapper doing the object mapping and then OData doing the stitching before a final result Serialize.

This would mean that the ORM doesn't need to be half as "smart".
